config/routes.rb
PropertyManager::Application.routes.draw do
  resources :properties

  resources :users, :only => [:new, :create, :show, :edit, :update] do
    member do 
      get :edit_password
      put :update_password
    end
  end
  resources :sessions, :only => [:new, :create]
  
  get '/design', :to => 'pages#design', :as => 'design'  
  get '/dashboard', :to => 'pages#dashboard', :as => 'dashboard'  
  get '/signup', :to => 'users#new'
  get '/login', :to => 'sessions#new', :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'
  root :to => "pages#test"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :properties, :foreign_key => "creator_id"

  attr_accessor :password, :edit_password, :update_password, :original_password
  attr_accessible :f_name, :l_name, :email, :password, :password_confirmation, :update_password, :signup_code, :original_password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :f_name,    :presence => true
  validates :l_name,    :presence => true
  validates :email,     :format   => { :with => email_regex }
  validates :password,  :length => { :minimum => 4, :maximum => 50 },
                        :confirmation => true,
                        :allow_blank => true
  validates :password, :presence => true, :if => :password_required?
  
  validate :validate_original_password
  
  VALID_SIGNUP_CODES = ["HAPPYNEWYEAR"]
  
  before_save :encrypt_password
  
  def name
    "#{f_name} #{l_name}"
  end
  
  def valid_password?(password_to_check)
    encrypted_password == encrypt(password_to_check) 
  end
  
  # Always check before create
  def signup_code_error    
    return I18n.t("message.no_signup_without_signup_code")  if signup_code.blank?
    return I18n.t("message.signup_code_invalid")            unless VALID_SIGNUP_CODES.include? signup_code
    return I18n.t("message.signup_code_used")               if User.find_by_signup_code(signup_code).present?
    nil
  end
  
  def validate_original_password
    if update_password.present?
      errors.add(:original_password, I18n.t("message.wrong_password")) unless valid_password?(original_password)
    end
  end
  
  private
    
  def password_required?
    !persisted? || update_password.present?
  end
  def encrypt_password
    if password_required?
      self.salt = make_salt
      self.encrypted_password = encrypt(password) 
    end
  end
  def make_salt
    secure_hash("#{Time.new.utc}::#{password}")
  end
  def encrypt(string)
    secure_hash("#{salt}::#{string}")
  end
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
include SignupCodeHelper

class UsersController < ApplicationController
  before_filter :authentication, :except => [:new, :create]

  def new
    @user = User.new(:signup_code => params[:signup_code])
    redirect_on_invalid_signup_code @user
  end

  def create
    @user = User.new(params[:user])
    return if redirect_on_invalid_signup_code @user
    if @user.save
      login(Session.new({
        :email => params[:user][:email], 
        :password => params[:user][:password]}))
      redirect_to root_path, :notice => t("message.user_registered")
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    authorize! :read, @user
  end
  
  def edit
    @user = User.find(params[:id])
    authorize! :update, @user
  end

  def update
    @user = User.find(params[:id])
    authorize! :update, @user
    if @user.update_attributes(params[:user].except(:password, :password_confirmation))
      redirect_to root_path, :notice => t("message.user_updated")
    else
      render :edit
    end    
  end
  
  def edit_password
    @user = User.find(params[:id])
  end
  
  def update_password
    @user = User.find(params[:id])
    authorize! :update, @user
    if @user.update_attributes(params[:user].merge(:update_password => 1))
      redirect_to root_path, :notice => t("message.password_updated")
    else
      render :edit_password
    end        
  end  
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= validation_messages @user %>
  <%= f.hidden_field(:signup_code) unless @user.persisted? %>
  <%= form_field(f, :f_name, :text, "half") %>
  <%= form_field(f, :l_name, :text, "half last") %>
  <%= form_field(f, :email, :text, "full") %>
  
  <% unless @user.persisted? %>
    <%= form_field(f, :password, :text, "half") %>    
    <%= form_field(f, :password_confirmation, :text, "half last") %>
  <% end %>
  
  <div class="actions">
    <%= link_to(t("link.back"), (@user.persisted? ? user_path(@user) : root_path), :class => "button bGray left") %>
    <%= f.submit(t("link.#{@user.persisted? ? "update" : "register"}"), :class => "button bBlue right") %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<% title "update_user" %>

<div class="contentMedium">
  <h1><%= t("title.update_user") %></h1>
  <%= render 'form' %>
</div>

app/views/users/edit_password.html.erb
<% title "update_password" %>

<div class="contentMedium">
  <h1><%= t("title.update_password") %></h1>
  
  <%= form_for @user, :url => update_password_user_path(@user) do |f| %>
    <%= validation_messages @user %>
    <%= form_field(f, :original_password, :password, "full") %>    
    <%= form_field(f, :password, :password, "full") %>    
    <%= form_field(f, :password_confirmation, :password, "full") %>

    <div class="actions">
      <%= link_to(t("link.back"), user_path(@user), :class => "button bGray left") %>
      <%= f.submit(t("link.update"), :class => "button bBlue right") %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% title "register_user" %>

<div class="contentMedium">
  <h1><%= t("title.register_user") %></h1>
  <%= render 'form' %>  
</div>

app/views/users/show.html.erb
<% title "profile" %>

<div class="contentMedium">
  <h1><%= t("title.profile") %></h1>
  
  <div class="form">    
    <div><%= display_field(@user, :f_name, :p) %></div>
    <div><%= display_field(@user, :l_name, :p) %></div>
    <div><%= display_field(@user, :email, :p) %></div>
  </div>
  <div class="actionBox">
    <%= link_to(t("link.change_password"), edit_password_user_path(@user), :class => "button bGray right") %> 
    <%= link_to(t("link.edit"), edit_user_path(@user), :class => "button bGray right") %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>