config/routes.rb
PropertyManager::Application.routes.draw do
  resources :properties

  resources :users, :only => [:new, :create, :show, :edit, :update] do
    member do 
      get :edit_password
      put :update_password
    end
  end
  resources :sessions, :only => [:new, :create]
  
  get '/design', :to => 'pages#design', :as => 'design'  
  get '/dashboard', :to => 'pages#dashboard', :as => 'dashboard'  
  get '/signup', :to => 'users#new'
  get '/login', :to => 'sessions#new', :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'
  root :to => "pages#test"
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  has_many :photos, :as => :photoable, :dependent => :destroy
  has_one :note, :as => :notable, :dependent => :destroy # Use max one note
  belongs_to :main_photo, :class_name => "Photo"
  
  accepts_nested_attributes_for :note, :photos
  attr_accessor :main_photo_index
  attr_accessible :city, :n_bathroom, :n_room, :postcode, :street, :suburb, :note_attributes, :photos_attributes, :main_photo_id, :main_photo_index
  
  before_save :update_main_photo, :remove_empty_note, :remove_unuse_photos
  
  def prepare_note_for_form
    self.note_attributes = {:note => nil}  if note.blank?
  end
  def prepare_photos_for_form
    self.photos.reload
    self.photos.build
  end
  def remove_empty_note
    note.destroy if note.present? && note.note.blank?
  end
  def remove_unuse_photos
    self.photos.each do |photo|
      puts photo.photo_delete
      photo.destroy if photo.photo.blank? || photo.photo_delete == "1"
    end
  end
  def update_main_photo
    if main_photo_index
      self.main_photo = photos[main_photo_index.to_i]
    else
      self.main_photo_id = nil
    end
    if main_photo_id.blank? && photos.present? 
      self.main_photo = photos.first
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :authentication
  # GET /properties
  # GET /properties.json
  def index
    @properties = current_user.properties
    @properties = paginate_records(@properties)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = current_user.properties.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = current_user.properties.build
    @property.prepare_note_for_form
    @property.prepare_photos_for_form
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = current_user.properties.find(params[:id])
    @property.prepare_note_for_form
    @property.prepare_photos_for_form
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = current_user.properties.build(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render json: @property, status: :created, location: @property }
      else
        @property.prepare_photos_for_form
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = current_user.properties.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        @property.prepare_photos_for_form
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = current_user.properties.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property, :html => { :multipart => true }) do |f| %>
  <%= validation_messages @property %>
  <%= form_field(f, :street, :text, "half") %>
  <%= form_field(f, :suburb, :text, "half last") %>
  <%= form_field(f, :city, :text, "half") %>
  <%= form_field(f, :postcode, :text, "half last") %>
  <%= form_field(f, :n_room, :number, "half") %>
  <%= form_field(f, :n_bathroom, :number, "half last") %>
  <%= f.fields_for :note do |v| %>
    <%= form_field(v, :note, :text, "full") %>
  <% end %>
  <div class="field full">
    <%= f.label(:photos, raw("Photos <div class='right'>Main</div>"), :class => "label") %>
    <% @property.photos.each_with_index do |photo, i| %>
      <%= f.fields_for :photos, photo do |v| %>
        <%= form_field_photo(f, v, i, :photo, "full", :file_text => t("message.browse_to_photo"), :no_label => true, :main_photo => (photo.id == @property.main_photo_id)) %>
      <% end %>
    <% end %>
  </div>
  <div class="actions">
    <% if @property.persisted? %>
      <%= link_to(t("link.back"), properties_path, :class => "button bGray left") %>
      <%= link_to(t("link.show"), property_path(@property), :class => "button bGray left") %>
      <%= f.submit(t("link.update"), :disable_with => t("link.updating"), :class => "button bBlue right") %>
    <% else %>
      <%= link_to(t("link.back"), properties_path, :class => "button bGray left") %>
      <%= f.submit(t("link.create"), :disable_with => t("link.creating"), :class => "button bBlue right") %>
    <% end %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="contentMedium">
  <% title "edit_property" %>
  <h1><%= t("title.edit_property") %></h1>
  <%= render 'form' %>
</div>

app/views/properties/index.html.erb
<% 
  title "properties"
  current_top_menu(:properties, :active)
%>

<h1><%= t("title.properties") %></h1>
<div id="propertyIndex">
  <% @properties.each do |property| %>
    <div class="property">
      <div class="propertyActions">
        <%= link_to 'Show', property %> |
        <%= link_to 'Edit', edit_property_path(property) %>
      </div>
      <div class="mainPhoto">
        <%= link_to (property.main_photo.present? ? image_tag(property.main_photo.photo_url(:small)) : t("message.no_photo")), property %>
      </div>
      <div class="address">
        <div class="street" title="<%= property.street %>"><%= link_to property.street, property %></div>
        <div class="suburbCity" title="<%= "#{property.suburb}, #{property.city}" %>"><%= "#{property.suburb}, #{property.city}" %></div>
        <div class="postcode"><%= property.postcode %></div>
      </div>
      <div class="dotDotDot"></div>
    </div>
  <% end %>
</div>


<%= paginate_list("properties_path", 2) %>

<div class="actions">
  <%= link_to t("link.new_property"), new_property_path, :class => "button bBlue right" %>  
</div>

app/views/properties/new.html.erb
<div class="contentMedium">
  <% title "new_property" %>
  <h1><%= t("title.new_property") %></h1>
  <%= render 'form' %>
</div>

app/views/properties/show.html.erb
<%
  title "show_property"
  current_top_menu(:properties, :semi_active) 
%>

<div class="contentMedium" id="propertyShow">
  <div class="form">
    <div class="photos">
      <% @property.photos.each do |photo| %>
        <div class="photo<%= " main" if (photo.id == @property.main_photo_id) %>">
        <%= image_tag(photo.photo_url(:small)) %>
      </div>
      <% end %>
    </div>
    <div class="clear"></div>
    <%= display_field(@property, :street, :p) %>
    <%= display_field(@property, :suburb, :p) %>
    <%= display_field(@property, :city, :p) %>
    <%= display_field(@property, :postcode, :p) %>
    <%= display_field(@property, :n_room, :p) %>
    <%= display_field(@property, :n_bathroom, :p) %>
    <%= display_field(@property.note, :note, :p) %>
  </div>
  <div class="actions">
    <%= link_to t("link.back"), properties_path, :class => "button bGray left" %>  
    <%= link_to t("link.edit"), edit_property_path(@property), :class => "button bGray left" %>
  </div>
</div>