config/routes.rb
PropertyManager::Application.routes.draw do
  resources :properties

  resources :users, :only => [:new, :create, :show, :edit, :update] do
    member do 
      get :edit_password
      put :update_password
    end
  end
  resources :sessions, :only => [:new, :create]
  
  get '/design', :to => 'pages#design', :as => 'design'  
  get '/dashboard', :to => 'pages#dashboard', :as => 'dashboard'  
  get '/signup', :to => 'users#new'
  get '/login', :to => 'sessions#new', :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'
  root :to => "pages#test"
end

app/views/layouts/_footer.html.erb
<div id="footer">
  
</div>

app/views/layouts/_head_tag.html.erb
<title>PropertyManager<%= yield :page_title %></title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>

app/views/layouts/_header.html.erb
<div id="headerWrapper">
  <div id="header">
    <%= render 'layouts/messages' %>
    <% unless current_user %>
      <div id="login"><%= link_to t("link.login"), login_path %></div>
    <% else %>
      <div id="profile">
        <div class="username"><%= current_user.name %></div>
        <ul>
          <li><%= link_to t("link.profile"), user_path(current_user) %></li>
          <li><%= link_to t("link.logout"), logout_path %></li>
        </ul>
      </div>
    <% end %>
    <div id="top_menu">
      <div class="menu"><%= top_menu_tag :dashboard %></div>
      <div class="menu"><%= top_menu_tag :properties %></div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if flash.count > 0 %>
  <div id="messagesWrapper"><div id="messages">
    <% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
    <% end %>
  </div></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head_tag' %>
</head>
<body>
<div id="fullsizeFrame">
  <%= render 'layouts/header' %>
  <div class="contentFull"><%= yield %></div>
  <div class="push"></div>
</div>
<%= render 'layouts/footer' %>
</body>
</html>